apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-consultancy-akvo-flow-web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tech-consultancy-akvo-flow-web-api
  template:
    metadata:
      labels:
        run: tech-consultancy-akvo-flow-web-api
        code-version: ${TRAVIS_COMMIT}
    spec:
      containers:
      - name: tech-consultancy-akvo-flow-web-api
        image: eu.gcr.io/akvo-lumen/tech-consultancy-akvo-flow-web-api:${TRAVIS_COMMIT}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 1
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: tech-consultancy-akvo-flow-web-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    run: tech-consultancy-akvo-flow-web-api
