"""Form instance

Revision ID: 4dfc574673d6
Revises: 
Create Date: 2020-06-01 18:51:08.205224

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4dfc574673d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_instance',
                    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()::varchar'), nullable=False),
                    sa.Column('state', sa.String(), nullable=False),
                    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('state')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_instance')
    # ### end Alembic commands ###
