"""Add meta column

Revision ID: 7eefbc517261
Revises: b7348ae12596
Create Date: 2020-11-28 05:34:42.923185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7eefbc517261"
down_revision = "b7348ae12596"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "form_instance",
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_instance", "meta")
    # ### end Alembic commands ###
