"""Form instance

Revision ID: e6e331cf259c
Revises: 
Create Date: 2020-06-01 16:52:35.939433

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e6e331cf259c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_instance',
                    sa.Column('id', sa.String(), server_default='gen_random_uuid()', nullable=False),
                    sa.Column('state', sa.String(), nullable=False),
                    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('state')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_instance')
    # ### end Alembic commands ###
