<?php

$old_variable = [
    'hh_size' => 'hh_size',
    'hh_head_gender' => 'hh_head_gender',
    'hh_size_male' => 'hh_size_male',
    'hh_size_female' => 'hh_size_female',
    'hh_gender_farmer' => 'hh_gender_farmer',
    'fs_shortage_months' => 'fs_shortage_months',
    'hh_age_farmer' => 'hh_age_farmer',
    'hh_education_farmer' => 'hh_education_farmer',
    'f_ownership' => 'f_ownership',
    'f_harvests' => 'f_harvests',
    'f_lost (kilograms)' => 'f_lost (kilograms)',
    'f_first_crop' => 'f_first_crop',
    'f_second_crop' => 'f_second_crop',
    'f_third_crop' => 'f_third_crop',
    'f_other_crop_income' => 'f_other_crop_income',
    'f_inputs_usage' => 'f_inputs_usage',
    'f_equipment_usage' => 'f_equipment_usage',
    'f_size (acre)' => 'f_size (acre)',
    'f_sdm_size (acre)' => 'f_sdm_size (acre)',
    'f_livestock' => 'f_livestock',
    'f_crops' => 'f_crops',
    'f_type' => 'f_type',
    'g_education' => 'g_education',
    'g_reprod_activities' => 'g_reprod_activities',
    'pi_location_cascade_county' => 'pi_location_cascade_county',
    'farmer_sample' => 'farmer_sample',
];

$new_variable = [
    'hh_size' => 'hh_size',
    'hh_head_gender' => 'hh_head_gender',
    'hh_size_male' => 'hh_male_nr',
    'hh_size_female' => 'hh_female_nr',
    'hh_gender_farmer' => 'hh_farmer_gender',
    'fs_shortage_months' => 'fs_shortage_months',
    'hh_age_farmer' => 'hh_farmer_age',
    'hh_education_farmer' => 'hh_education_farmer',
    'f_ownership' => 'f_ownership_type',
    'f_harvests' => 'f_harvest_num',
    'f_lost (kilograms)' => 'cal_focus_quant_lost',
    'f_first_crop' => 'f_othermaincrop_1',
    'f_second_crop' => 'f_othermaincrop_2',
    'f_third_crop' => null,
    'f_other_crop_income' => 'cal_other_crop_income',
    'f_inputs_usage' => 'f_inputs_usage',
    'f_equipment_usage' => [
        'f_nonmech_equip_type',
        'f_mech_equip_type',
        'f_materials_other_type'
    ],
    'f_size (acre)' => 'f_size (acre)',
    'f_sdm_size (acre)' => 'f_focus_crop_size (acre)',
    'f_livestock' => 'f_livestock_income_type',
    'f_crops' => ['f_othermaincrop_1', 'f_othermaincrop_2'],
    'f_type' => null,
    'g_education' => 'g_education',
    'g_reprod_activities' => 'g_reprod_activities',
    'pi_location_cascade_county' => 'pi_location_cascade_county',
    'farmer_sample' => 'farmer_sample',
];

$new_variable_with_diff_county = $new_variable;
$new_variable_with_diff_county['pi_location_cascade_county'] = 'pi_location_cascade_region';

return [
    'old_variable' => $old_variable,
    'fids' => [143920001, 145035285, 139002776, 150980836],
    'mapping' => [
        // Smart logistics - Beans
        [
            'fid' => 143920001,
            'variable' => $new_variable,
        ],
        // Syngenta Potatoes
        [
            'fid' => 145035285,
            'variable' => $new_variable,
        ],
        // Syngenta Tomatoes
        [
            'fid' => 139002776,
            'variable' => $new_variable,
        ],
        // USSL Tanzania - Maize
        [
            'fid' => 150980836,
            'variable' => $new_variable_with_diff_county,
        ],
    ],
    'number_type' => [
        'f_number_of_crops',
        'f_size (acre)',
        'f_focus_crop_size (acre)',
        'f_size_othermaincrop_1 (acre)',
        'f_size_othermaincrop_2 (acre)',
        'f_focuscrop_keep_seeds',
        'f_focuscrop_kept_planted',
        'f_harvest_num',
        'f_focuscrop_sold_seeds',
        'f_cost_seeds_sold',
        'f_othermaincrop_1_quant_prod',
        'f_othermaincrop_1_quant_sold',
        'f_othermaincrop_1_inc_sold',
        'f_other_crop_income',
        'f_livestcok_income_chickens',
        'f_costs_land',
        'f_costs_land_focuscrop',
        'f_nonfarm_enterpr_nr',
        'f_nonfarm_enterpr_1_permlabour_nr',
        'f_nonfarm_enterpr_1_permlabour_fem',
        'f_nonfarm_enterpr_1_permlabour_u35',
        'f_nonfarm_enterpr_1_permlabour_wage',
        'f_nonfarm_enterpr_1_caslabour_nr',
        'f_nonfarm_enterpr_1_caslabour_fem',
        'f_nonfarm_enterpr_1_caslabour_u35',
        'f_nonfarm_enterpr_1_caslabour_wage',
        'm_crops_livestock_contract_duration',
        'hh_loan_size',
        'hh_loan_months_to_repay',
        'hh_loan_costs_interest',
        'hh_loan_interest_rate_sdm',
        'hh_loan_interest_rate_bank',
        'hh_loan_interest_rate_mobile',
        'hh_loan_interest_rate_friend',
        'hh_loan_interest_rate_vsla',
        'cal_labour_landprep_alltimeframes',
        'cal_labour_cropmaint_alltimeframes',
        'cal_labour_fertilizerapp_alltimeframes',
        'cal_labour_harvesting_alltimeframes',
        'cal_labour_postharvest_alltimeframes',
        'cal_focus_measurement_prod',
        'cal_focus_quant_prod',
        'cal_focus_productivity',
        'cal_focus_quant_sold',
        'cal_focus_revenue',
        'cal_focus_quant_lost',
        'cal_focus_quant_own_consumption',
        'cal_focus_measurement_sold',
        'cal_labour_cropmaint_price',
        'cal_labour_cropmaint_cost',
        'cal_livestock_income',
        'cal_labour_landprep_price',
        'cal_offfarm_labour_income',
        'cal_labour_landprep_cost',
        'cal_labour_nurserymaint_price',
        'cal_labour_nurserymaint_cost',
        'cal_livestock_inputs_cost',
        'cal_livestock_cost',
        'cal_offfarm_income',
        'cal_othermaincrop_cost',
        'cal_labour_fertilizerapp_price',
        'cal_labour_cost',
        'cal_farm_cost',
        'cal_farm_general_cost',
        'cal_offfarm_non_labour_income',
        'cal_inputs_costs',
        'cal_equipment_costs',
        'cal_livestock_revenu',
        'cal_focus_lost_measurement',
        'cal_labour_fertilizerapp_cost',
        'cal_labour_harvesting_price',
        'cal_labour_harvesting_cost',
        'cal_labour_postharvest_price',
        'cal_labour_postharvest_cost',
        'cal_livestock_labour_cost',
        'cal_othermaincrop_income',
        'cal_other_crop_income',
        'cal_farm_revenu',
        'cal_farm_income',
        'cal_actual_income',
        'cal_focus_price',
        'hh_size',
        'hh_male_nr',
        'hh_female_nr',
        'hh_member_age',
        'hh_female_nr',
        'hh_head_age',
        'hh_farmer_age',
        'hh_unpaidlabour_hhactivities_hrs',
        'cs_sdm_company_services_years',
        'cs_sdm_company_yrs_selling',
        'cs_sdm_company_contract_durations',

    ],
];