apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tech-consultancy-appsa-api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tech-consultancy-appsa-api
  template:
    metadata:
      labels:
        run: tech-consultancy-appsa-api
        code-version: ${TRAVIS_COMMIT}
    spec:
      containers:
      - name: tech-consultancy-appsa-api
        image: eu.gcr.io/akvo-lumen/tech-consultancy-appsa-api:${TRAVIS_COMMIT}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 1
            memory: 200Mi
        env:
        - name: RSR_TOKEN 
          valueFrom:
            secretKeyRef:
              name: tech-consultancy-rsr-token
              key: rsr-token
---
---
apiVersion: v1
kind: Service
metadata:
  name: tech-consultancy-appsa-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    run: tech-consultancy-appsa-api
