FROM rstudio/plumber:v1.0.0

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
        libudunits2-dev \
        libgdal-dev \
        libgeos-dev \
        libproj-dev

RUN R -e "\
    install.packages('rmarkdown', repos='http://cran.rstudio.com/'); \
    install.packages('dplyr', repos='http://cran.rstudio.com/'); \
    install.packages('tidyr', repos='http://cran.rstudio.com/'); \
    install.packages('tidylog', repos='http://cran.rstudio.com/'); \
    install.packages('readr', repos='http://cran.rstudio.com/'); \
    install.packages('data.table', repos='http://cran.rstudio.com/'); \
    install.packages('ggplot2', repos='http://cran.rstudio.com/'); \
    install.packages('reshape2', repos='http://cran.rstudio.com/'); \
    install.packages('openxlsx', repos='http://cran.rstudio.com/'); \
    install.packages('Hmisc', repos='http://cran.rstudio.com/'); \
    install.packages('here', repos='http://cran.rstudio.com/'); \
    install.packages('zoo', repos='http://cran.rstudio.com/'); \
    install.packages('readxl', repos='http://cran.rstudio.com/'); \
    install.packages('splitstackshape', repos='http://cran.rstudio.com/'); \
    install.packages('sf', repos='http://cran.rstudio.com/'); \
    install.packages('jsonlite', repos='http://cran.rstudio.com/'); \
    install.packages('curl', repos='http://cran.rstudio.com/'); \
"

WORKDIR /usr/src/app