version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ../:/usr/src/app:delegated
    command: /usr/src/app/idh.R