apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-consultancy-2scale-login
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tech-consultancy-2scale-login
  template:
    metadata:
      labels:
        run: tech-consultancy-2scale-login
        code-version: ${TRAVIS_COMMIT}
    spec:
      containers:
      - name: tech-consultancy-2scale-login
        image: eu.gcr.io/akvo-lumen/tech-consultancy-2scale-login:${TRAVIS_COMMIT}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 1
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: tech-consultancy-2scale-login
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    run: tech-consultancy-2scale-login
