yarn remove jszip
yarn remove pdfmake
yarn remove datatables.net-bs4
yarn remove datatables.net-autofill-bs4
yarn remove datatables.net-buttons-bs4
yarn remove datatables.net-fixedcolumns-bs4
yarn remove datatables.net-responsive-bs4
yarn remove datatables.net-rowgroup-bs4
yarn remove datatables.net-rowreorder-bs4
yarn remove datatables.net-scroller-bs4
yarn remove datatables.net-select-bs4
